### ISSUE TITLE
Category doesn't show when first made

### ISSUE THREAD

**Issue by zacharyvincze** [zacharyvincze/OpenForum#3]
When first created.  The category won't show unless there is a topic made in it.

**Comment by Arinerron** [comment]
That's odd. Is there an error in the logs? Maybe the COUNT(*) isn't working well.

**Comment by zacharyvincze** [comment]
There's something wrong with the query in the index.php file.  Check it out and see what can be done about it.

**Comment by zacharyvincze** [comment]
Fixed, I couldn't use WHERE because it wouldn't return null values.

**Comment by Arinerron** [comment]
Congrats :tada:
