### ISSUE TITLE
XSS usernames

### ISSUE THREAD

**Issue by zacharyvincze** [zacharyvincze/OpenForum#5]
XSS usernames mess up the website.  They can't be added.

**Comment by zacharyvincze** [comment]
Thinking about adding htmlspecialchars to literally everything that requires user input.

**Comment by Arinerron** [comment]
@zacharyvincze That's generally a good idea. Keep in mind though that it should only htmlspecialchars before sending it to the client, but not while being stored in the database.

**Comment by Arinerron** [comment]
htmlspecialchars isn't required for the username (especially if it enforces alphanumeric ones), but is recommended.

**Comment by Arinerron** [comment]
Fixed in commit https://github.com/zacharyvincze/OpenForum/commit/a90f184e60e53f7ab830acf5988b7bf3499811ea
